App/urls.py
from django.urls import path
from App import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('userinfo/', views.userinfo, name='userinfo'),
    path('repassword/', views.repassword, name='repassword'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/<type>', views.dashboard, name='dashboard'),
    path('upload/', views.upload, name='upload'),
    path('image/', views.listImage, name='image'),
    path('tasklist/', views.listTask, name='listTask'),
    path('taskadd/', views.addTask, name='addTask'),
    path('taskcheck/<id>', views.checkTask, name='checkTask'),
    path('edit/<id>', views.editMD, name='editMD'),
    path('paperlist/', views.paperList, name='paperList'),
    path('paperview/<id>', views.paperDetail, name='paperDetail'),
    path('video/<id>', views.videoView, name='videoView'),
    path('videolist/', views.videoList, name='videoList'),
    # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    path('videoView/', views.stream_video, name='stream_video'),
    path('videoDownload/<id>', views.videoDownload, name='videoDownload'),
    path('packagelist/', views.packagelist, name='packagelist'),
    path('packageDownload/<id>', views.packageDownload, name='packageDownload'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('App.urls','App'), namespace='App')),
    path('admin/', admin.site.urls),
]

templates/task/detailed.html
{% extends 'template.html' %}
{% block title %}
    <title>任务查看</title>
{% endblock %}
{% block content %}
    <div class="container" style="padding-top: 70px">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">姓名</th>
                    <th scope="col">状态</th>
                    <th scope="col">更新时间</th>
                    <th scope="col">操作</th>
                </tr>
                </thead>
                <tbody>
                {% for k,v in data.items %}
                    {% if v.status == '未完成' %}
                        <tr class="table-danger">
                            {% else %}
                        <tr class="table-success">
                    {% endif %}
                <td>{{ k }}</td>
                <td>{{ v.status }}</td>
                <td>{{ v.update_time }}</td>
                <td>
                    {% if v.status == '未完成' %}
                        <form action="{% url 'App:checkTask' id %}?name={{ k }}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="点击完成">
                        </form>
                    {% else %}
                        <input type="submit" value="已完成任务">
                    {% endif %}
                </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block foot %}
{% endblock %}

templates/task/taskcreate.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>注册</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/checkout/">

    {% load static %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/station/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .col-center {
            float: none;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/station/form-validation.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/station/list-groups.css' %}">
</head>
<body class="bg-light">

<div class="container">
    <main>
        <div class="py-5 text-center">
            <img class="d-block mx-auto mb-4" src="{% static 'images/bootstrap-logo.svg' %}" alt="" width="72"
                 height="57">
            <h2>任务创建</h2>
            <p class="lead">创建任务，平台正在测试中，如遇BUG，请点击页面下方提交反馈</p>
        </div>
        <form class="needs-validation" novalidate method="post">
            {% csrf_token %}
            <div class="col-md-7 col-lg-8 col-center">
                <div class="row g-3">
                    <div class="col-12">
                        <label for="user" class="form-label">标题</label>
                        <input type="text" class="form-control" id="title" placeholder=""
                               name="title" value=""
                               required>
                        <div class="invalid-feedback">
                            请输入标题
                        </div>
                    </div>
                    <div class="col-12">
                        <label for="user" class="form-label">封面链接&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'App:upload' %}" target="_blank">点击上传封面图片</a></label>
                        <input type="text" class="form-control" id="bimage" placeholder="可以为空，为空则不显示封面"
                               name="bimage" value="">
                        <div class="invalid-feedback">
                            请输入标题
                        </div>
                    </div>
                    <div class="col-12">
                        <label for="userlist" class="form-label">人员名单</label>
                        <input type="text" class="form-control" id="userlist" placeholder="多个姓名，请使用英文逗号','隔开"
                               name="userlist" value=""
                               required>
                        <div class="invalid-feedback">
                            姓名必须填写
                        </div>
                    </div>

                    <div class="col-12">
                        <label for="desc" class="form-label">描述信息</label>
                        <input type="text" class="form-control" name="desc" id="desc"
                               placeholder="填写任务的描述性信息，这个很重要，需要以此来确定任务完成需求" required>
                        <div class="invalid-feedback">
                            描述信息必须填写
                        </div>
                    </div>
                </div>
                <hr class="my-4">

                <button class="w-100 btn btn-primary btn-lg" type="submit">创建</button>
            </div>
        </form>
    </main>

    <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; 2017–2023 云计算学院</p>
        <ul class="list-inline">
            <li class="list-inline-item"><a href="#">BUG提交</a></li>
        </ul>
    </footer>
</div>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'js/form-validation.js' %}"></script>
</body>
</html>

templates/task/tasklist.html
{% extends 'template.html' %}
{% block title %}
    {% load static %}
    {% load myfilter %}
    <title>任务列表</title>
    <link href="{% static 'css/upload/features.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    {% load static %}
    <div style="padding-top: 70px">
        <section class="py-5 text-center container">
            <div class="row py-lg-2">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">作业平台</h1>
                    <p class="lead text-muted">作业平台仅供内部成员使用，目前依旧在测试阶段，功能正不断更新</p>
                    <p>
                        <a href="{% url 'App:addTask' %}" class="btn btn-primary my-2">创建任务</a>
                        <a href="#" class="btn btn-secondary my-2">BUG提交</a>
                    </p>
                </div>
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">

                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for i in task %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <img class="bd-placeholder-img card-img-top" width="100%" height="225"
                                     src="{{ i.task_content | setjson:"backend_image" }}" role="img"
                                     aria-label="Placeholder: Thumbnail"
                                     preserveAspectRatio="xMidYMid slice" focusable="false">
                                <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ i.task_title }}</text>
                                <rect width="100%" height="100%" fill="#55595c"/>
                                <div class="card-body">
                                    <p class="card-text">{{ i.task_content | setjson:"desc" }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'App:checkTask' i.id %}">
                                                <button type="button" class="btn btn-sm btn-outline-secondary">查看
                                                </button>
                                            </a>
                                            <button type="button"
                                                    class="btn btn-sm btn-outline-secondary">{{ i.task_content | checkover:'未完成' }}</button>
                                        </div>
                                        <small class="text-muted">{{ i.task_time }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}