App/urls.py
from django.urls import path
from App import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('userinfo/', views.userinfo, name='userinfo'),
    path('repassword/', views.repassword, name='repassword'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/<type>', views.dashboard, name='dashboard'),
    path('upload/', views.upload, name='upload'),
    path('image/', views.listImage, name='image'),
    path('tasklist/', views.listTask, name='listTask'),
    path('taskadd/', views.addTask, name='addTask'),
    path('taskcheck/<id>', views.checkTask, name='checkTask'),
    path('edit/<id>', views.editMD, name='editMD'),
    path('paperlist/', views.paperList, name='paperList'),
    path('paperview/<id>', views.paperDetail, name='paperDetail'),
    path('video/<id>', views.videoView, name='videoView'),
    path('videolist/', views.videoList, name='videoList'),
    # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    path('videoView/', views.stream_video, name='stream_video'),
    path('videoDownload/<id>', views.videoDownload, name='videoDownload'),
    path('packagelist/', views.packagelist, name='packagelist'),
    path('packageDownload/<id>', views.packageDownload, name='packageDownload'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('App.urls','App'), namespace='App')),
    path('admin/', admin.site.urls),
]

templates/function/edit.html
{% extends 'template.html' %}
    {% load static %}
{% block title %}
    <meta charset="utf-8"/>
    <title>文章编辑</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/editormd.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/station/bootstrap.min.css' %}"/>
    <link rel="shortcut icon" href="https://pandao.github.io/editor.md/favicon.ico" type="image/x-icon"/>
{% endblock %}
{% block content %}
<body onbeforeunload="event.returnValue='未保存'">
<div id="layout" style="height: 800px;background: #f6f6f6;padding-top: 70px">
    <form action="" method="post">
        <header style="margin-left: 200px">
            <div class="row g-3">
                <div class="col-sm-3">
                    <input type="text" class="form-control h-100" id="title" name="title" placeholder="此处填写标题" value=""
                           required>
                    <div class="invalid-feedback">
                        标题必须填写
                    </div>
                </div>

                <div class="col-sm-3">
                    <input type="text" maxlength=80 class="form-control h-100" id="desc" name="desc" placeholder="此处填写描述" value="">
                </div>
                <div class="col-sm-1">
                    <button class="w-100  h-100 btn btn-lg btn-primary" id="save" type="submit">保存
                    </button>
                </div>
            </div>
            <hr>
        </header>
        <div id="test-editormd">
            <textarea style="display:none;">{{ data.paper_content }}</textarea>
        </div>
    </form>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/editormd.js' %}"></script>
<script type="text/javascript">
    $(function () {
        var testEditor = editormd("test-editormd", {
            width: "90%",
            height: "650px",
            markdown: "",
            path: '../static/js/lib/',
            //autoHeight      : true,
            fontSize: "14px",
            //dialogLockScreen : false,   // 设置弹出层对话框不锁屏，全局通用，默认为 true
            //dialogShowMask : false,     // 设置弹出层对话框显示透明遮罩层，全局通用，默认为 true
            //dialogDraggable : false,    // 设置弹出层对话框不可拖动，全局通用，默认为 true
            //dialogMaskOpacity : 0.4,    // 设置透明遮罩层的透明度，全局通用，默认值为 0.1
            //dialogMaskBgColor : "#000", // 设置透明遮罩层的背景颜色，全局通用，默认为 #fff
            imageUpload: true,
            imageFormats: ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
            imageUploadURL: "{% url 'App:upload' %}?type=editmd",

            /*
             上传的后台只需要返回一个 JSON 数据，结构如下：
             {
                success : 0 | 1,           // 0 表示上传失败，1 表示上传成功
                message : "提示的信息，上传成功或上传失败及错误信息等。",
                url     : "图片地址"        // 上传成功时才返回
             }
             */
        });
    });
    {% if data %}
        $('#title').val('{{ data.paper_title }}');
        $('#desc').val('{{ data.paper_desc }}');
    {% endif %}
</script>
</body>
{% endblock %}
{% block foot %}
{% endblock %}

templates/function/user.html
{% extends 'template.html' %}
{% block title %}
    {% load static %}
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
    <style>
        .container {
            margin: auto 50px;
            padding-top: 10px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <br><br><br>
        <h1>你好，{{ name }}</h1>
        <p class="fs-5 col-md-8">本站点功能依旧在开发当中，欢迎你的使用及反馈，以下为你在本站的操作轨迹。</p>
        <p class="fs-5 col-md-8">注册时间：{{ regtime }}</p>
        <hr style="border: 5px solid blue;"/>
        <p>版本更新日志：v1.10.11</p>
        <p>1、版本修改了登录逻辑，不在记录非公网的登录位置</p>
        <p>2、优化注册页面</p>
        <p>3、新增文件上传下载功能</p>
        <p>4、优化了图片显示方式</p>
        <p>5、用户界面添加视频及文件归档</p>
        <p>6、增加仪表盘界面的文件上传数据</p>
        <div class="mb-5">
            <a href="{% url 'App:repassword' %}" class="btn btn-primary btn-lg px-4">修改密码</a>
        </div>

        <hr style="border: 5px solid blue;"/>

        <div class="row g-5">
            <div class="col-md-6">
                <h2>最近登录</h2>
                <p>显示5次最近登录时数据，获取所有数据请联系管理员</p>
                <ul class="icon-list">
                    {% for i in login_data %}
                        <li>登录时间：{{ i.login_time }}&nbsp;&nbsp;登录地址：{{ i.client_addr }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6">
                <h2>文件存储</h2>
                <p>显示5次最近文件上传时数据，获取所有数据查看 <a href="{% url 'App:packagelist' %}">文件库</a></p>
                <ul class="icon-list">
                    {% for i in package_data %}
                        <li>上传时间：{{ i.package_time }}&nbsp;&nbsp;下载地址： <a href="{% url 'App:packageDownload' i.id %}">{{ i.package_title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6">
                <h2>视频存储</h2>
                <p>显示5次最近视频上传数据，获取所有数据查看{% url 'App:videoList' %}</p>
                <ul class="icon-list">
                    {% for i in video_data %}
                        <li>上传时间：{{ i.video_time }}&nbsp;&nbsp;观看地址：<a href="{% url 'App:videoView' i.id %}">{{ i.video_title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6">
                <h2>图床数据</h2>
                <p>最近5次，获取所有数据查看<a href="{% url 'App:image' %}">我的相册</a></p>
                <ul class="icon-list">
                    {% for i in image_data %}
                        <li>
                            <a href="{{ i.url_path }}">图片链接</a>&nbsp;&nbsp;{{ i.upload_time }}&nbsp;&nbsp;{{ i.file_name |truncatechars:20 }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6">
                <h2>文章数据</h2>
                <p>最近5次，获取所有数据查看<a href="{% url 'App:paperList' %}">文章列表</a></p>
                <ul class="icon-list">
                    {% for i in blog_data %}
                        <li>
                            <a href="{% url 'App:editMD' i.id %}">文章链接</a>&nbsp;&nbsp;{{ i.paper_time }}&nbsp;&nbsp;文章标题：{{ i.paper_title }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6">
                <h2>任务事件</h2>
                <p>最近5次，获取所有数据查看<a href="{% url 'App:listTask' %}">任务数据</a></p>
                <ul class="icon-list">
                    {% for i in task_data %}
                        <li>
                            <a href="{% url 'App:checkTask' i.id %}">事件链接</a>&nbsp;&nbsp;创建时间：{{ i.task_time }}&nbsp;&nbsp;事件名称：{{ i.task_title }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <hr style="border: 5px solid blue;"/>
        </div>
    </div>
{% endblock %}

templates/function/viewmd.html
{% extends 'template.html' %}
    {% load static %}
{% block title %}
    <meta charset="utf-8"/>
    <title>{{ data.paper_title }}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/editormd.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/station/bootstrap.min.css' %}"/>
    <link rel="shortcut icon" href="https://pandao.github.io/editor.md/favicon.ico" type="image/x-icon"/>
{% endblock %}
{% block content %}
<div id="layout" style="padding-top: 80px; height: 800px;background: #f6f6f6;">
    <div class="btns">
        <p style="display:inline; font-size: 20px">标题：{{ data.paper_title }}</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button id="print-btn" class="btn-success text-dark">打印</button>
        <button id="preview-btn" class="btn-success text-dark">切换模式</button>
        <form action="" method="post" style="margin:0 auto;display:inline;">
            {% csrf_token %}
            <button class="btn-success text-dark">赞<img src="{% static 'images/thumbs.jpg' %}" width="20" height="20">{{ thumbs }}</button>
        </form>
    </div>
    <div id="test-editormd">
        <textarea style="display:none;">{{ data.paper_content }}</textarea>
    </div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/editormd.js' %}"></script>
<script type="text/javascript">
    $(function () {
        var testEditor = editormd("test-editormd", {
            width: "90%",
            height: 650,
            saveHTMLToTextarea: true,
            watch: false,
            path: "{% static 'js/lib/' %}",
            //watch           : false,           // disable watch
            readOnly: true,
            styleActiveLine: false,   // disable active line
            //lineNumbers     : false      // hide line numbers
        });
        $("#preview-btn").click(function () {
            testEditor.previewing();
        });
        $("#print-btn").click(function () {
            var html = testEditor.preview.html();
            document.write('<link rel="stylesheet" href="{% static 'css/style.css' %}" /><link rel="stylesheet" href="{% static 'css/editormd.css' %}" />' + html);
            window.print();
        });
    });
</script>
{% endblock %}
{% block foot %}
{% endblock %}