App/urls.py
from django.urls import path
from App import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('userinfo/', views.userinfo, name='userinfo'),
    path('repassword/', views.repassword, name='repassword'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/<type>', views.dashboard, name='dashboard'),
    path('upload/', views.upload, name='upload'),
    path('image/', views.listImage, name='image'),
    path('tasklist/', views.listTask, name='listTask'),
    path('taskadd/', views.addTask, name='addTask'),
    path('taskcheck/<id>', views.checkTask, name='checkTask'),
    path('edit/<id>', views.editMD, name='editMD'),
    path('paperlist/', views.paperList, name='paperList'),
    path('paperview/<id>', views.paperDetail, name='paperDetail'),
    path('video/<id>', views.videoView, name='videoView'),
    path('videolist/', views.videoList, name='videoList'),
    # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    path('videoView/', views.stream_video, name='stream_video'),
    path('videoDownload/<id>', views.videoDownload, name='videoDownload'),
    path('packagelist/', views.packagelist, name='packagelist'),
    path('packageDownload/<id>', views.packageDownload, name='packageDownload'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('App.urls','App'), namespace='App')),
    path('admin/', admin.site.urls),
]

templates/index.html
{% extends 'template.html' %}
{% block title %}
    <title>主页</title>
{% endblock %}
{% block link %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/station/carousel.css' %}">
{% endblock %}
{% block login %}
    <header style="padding-top: 70px">
        <div class="px-3 py-2 border-bottom mb-3">
            <div class="container d-flex flex-wrap justify-content-center">
                <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto">
                    <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
                </form>
                {% if not name %}
                    <div class="text-end">
                        <a href="{% url 'App:login' %}">
                            <button type="button" class="btn btn-light text-dark me-2">登录</button>
                        </a>
                        <a href="{% url 'App:register' %}">
                            <button type="button" class="btn btn-primary">注册</button>
                        </a>
                    </div>
                {% else %}
                    <div class="text-end">
                        <a href="{% url 'App:logout' %}">
                            <button type="button" class="btn btn-light text-dark me-2">退出登录</button>
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    </header>
{% endblock %}
{% block content %}
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true"
                    aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images/index/index1.jpg' %}" alt="First slide"> %}" alt="">

                <div class="container">
                    <div class="carousel-caption text-start">
                        <h1>NewRain 个人网盘</h1>
                        <p>教学资料，随堂视频，各种资料开源下载</p>
                        <p><a class="btn btn-lg btn-primary" href="https://www.beyourself.org.cn"
                              target="_blank">点击访问</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/index/index2.jpg' %}" alt="First slide"> %}" alt="">

                <div class="container">
                    <div class="carousel-caption">
                        <h1>NewRain 代码仓库</h1>
                        <p>教学代码实例，多看多敲，开卷！</p>
                        <p><a class="btn btn-lg btn-primary" href="https://gitee.com/newrain001"
                              target="_blank">点击跳转</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/index/index3.jpg' %}" alt="First slide"> %}" alt="">

                <div class="container">
                    <div class="carousel-caption text-end">
                        <h1>面试内容整理</h1>
                        <p>美好生活，来源于自我努力</p>
                        <p><a class="btn btn-lg btn-primary" href="https://interview.beyourself.org.cn" target="_blank">点击查看</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="{% static 'images/tuchuang.jpg' %}" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#777"/>
                </img>

                <h2>便捷图床</h2>
                <p>将图片上传到云端对象存储，并获取便捷的链接方式，请放心，您的图片会被永久保存，也可以随时下载，您的图片可以再<a href="{% url 'App:image' %}">我的相册</a>中查看</p>
                <p><a class="btn btn-secondary" href="{% url 'App:upload' %}">点击跳转</a></p>
            </div>
            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="{% static 'images/work.jpg' %}" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#777"/>
                </img>

                <h2>任务处理</h2>
                <p>请在规定时间内完成规定任务，此功能仅支持内部使用，任务下达会在课堂中提醒，任务完成过程中请截图保留。未完成将得到奖励、</p>
                <p><a class="btn btn-secondary" href="{% url 'App:listTask' %}">点击查看</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="{% static 'images/paper.jpg' %}" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"></img>

                <h2>文章发表</h2>
                <p>发表文章，如果你有好的文章，又愿意共享，请点击此处，注意：文章格式采用markdown格式编写，markdown格式编写，请自行学习。点击查看<a
                        href="{% url 'App:paperList' %}">博文列表</a></p>
                <p><a class="btn btn-secondary" href="{% url 'App:editMD' 'new' %}">立即开始</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="{% static 'images/package.jpg' %}" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"></img>

                <h2>文件上传</h2>
                <p>课程文件上传<a
                        href="{% url 'App:packagelist' %}">文件库</a></p>
                <p><a class="btn btn-secondary" href="{% url 'App:upload' %}?type=package">立即上传</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                     src="{% static 'images/video.jpg' %}" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"></img>

                <h2>视频上传</h2>
                <p>随堂视频播放<a
                        href="{% url 'App:videoList' %}">视频库</a></p>
                <p><a class="btn btn-secondary" href="{% url 'App:upload' %}?type=videos">立即上传</a></p>
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
        <hr>
        {% for k,v in data.items %}
            <div class="row featurette">
                <div class="col-md-7">
                    <h2 class="featurette-heading"><a href="{{ k }}" target="_blank"
                                                      style="text-decoration: none;">{{ v.title }}</a></h2>
                    <hr>
                    <p class="lead">{{ v.text | truncatechars:100 }}</p>
                </div>
                <div class="col-md-5">
                    <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500"
                         height="500" src="{{ v.image }}" role="img" aria-label="Placeholder: 500x500"
                         preserveAspectRatio="xMidYMid slice" focusable="false"></img>
                </div>
            </div>
            <hr>
        {% endfor %}
        <!-- /END THE FEATURETTES -->
    </div><!-- /.container -->
{% endblock %}

templates/login.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>登录</title>

    {#    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">#}

    {% load static %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/station/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/station/signin.css' %}" rel="stylesheet">
</head>
<body class="text-center">

<main class="form-signin">
    <form method="post">
        {% csrf_token %}
        <img class="mb-4" src="{% static 'images/bootstrap-logo.svg' %}" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">用户登录</h1>
        {% if errors %}
        <div class="alert alert-danger" role="alert">
           {{ errors.loginName }} {{ errors.loginPass }}
        </div>
        {% endif %}

        <div class="form-floating">
            <input type="text" name="loginName" class="form-control" id="floatingInput" required placeholder="用户名">
            <label for="floatingInput">用户名</label>
        </div>
        <div class="form-floating">
            <input type="password" name="loginPass" class="form-control" id="floatingPassword" required
                   placeholder="Password">
            <label for="floatingPassword">密码</label>
        </div>

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me">&nbsp;&nbsp;记住密码
            </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">登录</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017–2023</p>
    </form>
</main>


</body>
</html>

templates/register.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>注册</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/checkout/">

    {% load static %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/station/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/station/form-validation.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/station/list-groups.css' %}">
</head>
<body class="bg-light">

<div class="container">
    <main>
        <div class="py-5 text-center">
            <img class="d-block mx-auto mb-4" src="{% static 'images/bootstrap-logo.svg' %}" alt="" width="72"
                 height="57">
            <h2>注册</h2>
            <p class="lead">请您填写一下信息，注册您的个人账号，请放心，您的信息会被严格保密。</p>
        </div>
        <form class="needs-validation" novalidate method="post">
            {% csrf_token %}
            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last float-right">
                    <div class="list-group">
                        <label class="list-group-item d-flex gap-3">
                            <input class="form-check-input flex-shrink-0" type="checkbox" name="like" value="like1"
                                   checked
                                   style="font-size: 1.375em;">
                            <span class="pt-1 form-checked-content">
      <strong>web架构</strong>
      <small class="d-block text-muted">
        <svg class="bi me-1" width="1em" height="1em"><use xlink:href="#calendar-event"/></svg>
      </small>
    </span>
                        </label>
                        <label class="list-group-item d-flex gap-3">
                            <input class="form-check-input flex-shrink-0" type="checkbox" name="like" value="like2"
                                   style="font-size: 1.375em;">
                            <span class="pt-1 form-checked-content">
      <strong>云原生</strong>
      <small class="d-block text-muted">
        <svg class="bi me-1" width="1em" height="1em"><use xlink:href="#calendar-event"/></svg>
      </small>
    </span>
                        </label>
                        <label class="list-group-item d-flex gap-3">
                            <input class="form-check-input flex-shrink-0" type="checkbox" name="like" value="like3"
                                   style="font-size: 1.375em;">
                            <span class="pt-1 form-checked-content">
      <strong>基础运维</strong>
      <small class="d-block text-muted">
        <svg class="bi me-1" width="1em" height="1em"><use xlink:href="#alarm"/></svg>
      </small>
    </span>
                        </label>
                    </div>
                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">填写信息</h4>
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="firstName" class="form-label">姓</label>
                            <input type="text" class="form-control" id="firstName" placeholder="" name="fname" value=""
                                   required>
                            <div class="invalid-feedback">
                                姓名必须填写
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <label for="lastName" class="form-label">名</label>
                            <input type="text" class="form-control" id="lastName" placeholder="" name="lname" value=""
                                   required>
                            <div class="invalid-feedback">
                                姓名必须填写
                            </div>
                        </div>

                        <div class="col-12">
                            <label for="username" class="form-label">登陆用户名</label>
                            <div class="input-group has-validation">
                                <input type="text" class="form-control" id="username" name="username" value=""
                                       placeholder="用于登录" required>
                                <div class="invalid-feedback">
                                    用户名必须填写
                                </div>
                            </div>
                        </div>

                        <div class="col-12">
                            <label for="email" class="form-label">邮箱 <span
                                    class="text-muted">(境内邮箱)</span></label>
                            <input type="email" class="form-control" name="email" id="email" placeholder="你的电子邮箱地址">
                            <div class="invalid-feedback">
                                邮箱必须填写
                            </div>
                        </div>
                        <div class="col-12">
                            <label for="id_password" class="form-label">密码 <span
                                    class="text-muted">(最小6位)</span></label>
                            <input type="password" class="form-control" name="password" id="id_password"
                                   placeholder="密码">
                            <div class="invalid-feedback">
                                密码
                            </div>
                        </div>
                    </div>
                    {% if errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ errors.password }} {{ errors.fname }} {{ errors.lname }} {{ errors.username }}
                    </div>
                    {% endif %}
                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">注册</button>
                </div>
            </div>
        </form>
    </main>

    <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; 2017–2023 云计算学院</p>
        <ul class="list-inline">
            <li class="list-inline-item"><a href="{% url 'App:index' %}">主页</a></li>
            <li class="list-inline-item"><a href="{% url 'App:login' %}">登录</a></li>
        </ul>
    </footer>
</div>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'js/form-validation.js' %}"></script>
</body>
</html>