App/urls.py
from django.urls import path
from App import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('userinfo/', views.userinfo, name='userinfo'),
    path('repassword/', views.repassword, name='repassword'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/<type>', views.dashboard, name='dashboard'),
    path('upload/', views.upload, name='upload'),
    path('image/', views.listImage, name='image'),
    path('tasklist/', views.listTask, name='listTask'),
    path('taskadd/', views.addTask, name='addTask'),
    path('taskcheck/<id>', views.checkTask, name='checkTask'),
    path('edit/<id>', views.editMD, name='editMD'),
    path('paperlist/', views.paperList, name='paperList'),
    path('paperview/<id>', views.paperDetail, name='paperDetail'),
    path('video/<id>', views.videoView, name='videoView'),
    path('videolist/', views.videoList, name='videoList'),
    # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    path('videoView/', views.stream_video, name='stream_video'),
    path('videoDownload/<id>', views.videoDownload, name='videoDownload'),
    path('packagelist/', views.packagelist, name='packagelist'),
    path('packageDownload/<id>', views.packageDownload, name='packageDownload'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('App.urls','App'), namespace='App')),
    path('admin/', admin.site.urls),
]

templates/nav/image.html
{% extends 'template.html' %}
{% load static %}
{% block title %}
    <title>我的相册</title>
    <link href="{% static 'css/upload/features.css' %}" rel="stylesheet">
    <style>
        small {
            font-size: 30px;
            color: red;
        }
    </style>
{% endblock %}
{% block content %}
    <div style="padding-top: 70px">
        <div class="container px-4 py-5">
            <h2 class="pb-2 border-bottom">我的相册</h2>
            <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
                {% for i in image %}
                    <div class="col">
                        <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg"
                             style="background-image: url({{ i.url_path }});">
                            <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
                                <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold"><a href="{{ i.url_path }}"
                                                                                     target="_blank">点击预览图片</a></h2>
                                <ul class="d-flex list-unstyled mt-auto">
                                    <li class="me-auto">
                                        <img src="{% static 'images/bootstrap-logo.svg' %}" alt="Bootstrap" width="32"
                                             height="32"
                                             class="rounded-circle border border-white">
                                    </li>
                                    <li class="d-flex align-items-center me-3">
                                        <svg class="bi me-2" width="1em" height="1em">
                                            <use xlink:href="#geo-fill"/>
                                        </svg>
                                        <small>{{ i.file_name }}</small>
                                    </li>
                                    <li class="d-flex align-items-center">
                                        <svg class="bi me-2" width="1em" height="1em">
                                            <use xlink:href="#calendar3"/>
                                        </svg>
                                        <small>{{ i.upload_time }}</small>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/nav/packagelist.html
{% extends 'template.html' %}
{% block title %}
    <title>文件下载</title>
    {% load static %}
{% endblock %}
{% block content %}
    <div class="main" style="padding-top: 80px">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">文件名称</th>
            <th scope="col">所属者</th>
            <th scope="col">上传时间</th>
            <th scope="col">文件大小</th>
            <th scope="col">下载次数</th>
        </tr>
        </thead>
        <tbody>
        {% for i in data %}
        <tr>
            <th scope="row">{{ i.id }}</th>
            <td><a href="{% url 'App:packageDownload' i.id %}">{{ i.package_title }}</a></td>
            <td>{{ i.username }}</td>
            <td>{{ i.package_time }}</td>
            <td>{{ i.package_size | filesizeformat }}</td>
            <td>{{ i.downloads }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/nav/paperlist.html
{% extends 'template.html' %}
{% load static %}
{% load myfilter %}
{% block title %}
    <title>博客列表</title>
    <link rel="stylesheet" href="{% static 'css/station/bootstrap.min.css' %}">
{% endblock %}
{% block content %}
    <div class="container" style="padding-top: 70px">
        <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
                <h1 class="display-4 fst-italic">文章列表</h1>
                <p class="lead my-3">文章由Markdown格式编写，语法请自行学习</p>
                <p class="lead mb-0"><a href="{% url 'App:editMD' 'new' %}" target="_blank"
                                        class="text-white fw-bold">创建文章</a></p>
            </div>
        </div>

        <div class="row mb-2">
            {% for i in data %}
                <div class="col-md-6">
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <strong class="d-inline-block mb-2 text-primary">作者:{{ i.username }}&nbsp;&nbsp;浏览:{{ i.views }}&nbsp;&nbsp;点赞:{{ thumbs |dict_get:i.id }}</strong>
                            <h3 class="mb-0">{{ i.paper_title }}</h3>
                            <div class="mb-1 text-muted">{{ i.paper_time }}</div>
                            <p class="card-text mb-auto">{{ i.paper_desc }}</p>
                            <div>
                                <a href="{% url 'App:paperDetail' i.id %}" target="_blank">阅读</a>
                                {% if i.username == username %}
                                <a href="{% url 'App:editMD' i.id %}" target="_blank">编辑</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            <img class="bd-placeholder-img" width="200" height="250" src="{{ i.paper_image }}"
                                 role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                                 focusable="false">
                                <rect width="100%" height="100%" fill="#55595c"/>
                            </img>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/nav/upload.html
{% extends 'template.html' %}
{% block title %}

{% endblock %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/station/bootstrap.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/station/bootstrap-icons.min.css' %}" crossorigin="anonymous">
    <link href="{% static 'css/upload/fileinput.css' %}" media="all" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/upload/all.css' %}" crossorigin="anonymous">
    <script src="{% static 'js/jquery.min.js' %}" crossorigin="anonymous"></script>
    <div class="container my-4" style="padding-top: 80px">
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"
                crossorigin="anonymous"></script>
        <script src="{% static 'js/fileinput.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/zh.js' %}" type="text/javascript"></script>
        <h4>文件上传</h4>
        <form enctype="multipart/form-data">
            {% csrf_token %}
            <label>请将文件拖拽到下列方框内</label>
            <div class="file-loading">
                <input id="file-fr" name="file" type="file" multiple>
            </div>
            <hr style="border: 2px dotted">
        </form>
        <hr>
        <span class="output"></span>
        <br>
    </div>
    </body>
    <script>
        $('#file-fr').fileinput({
            theme: 'fas',
            language: 'zh',
            uploadUrl: '{% url 'App:upload' %}?type={{ type }}',
            allowedFileExtensions: ['jpg', 'png', 'gif','mp4', 'gz', 'zip', 'exe', 'xz', 'tar'],
            uploadExtraData: function () {
                return {
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                };
            },

        }).on('fileuploaded', function (event, data) {
            var form = response = data.response;
            if (form.status === 'success') {
                console.log(form);
                for (var i = 0; i < form.msg.length; i++) {
                    var text = '<div class="alert alert-success" role="alert">' +
                        '<strong>' +
                        '文件名称：' + form.msg[i].filename + '<br>文件大小：' + form.msg[i].filesize / 1024 + 'KB' +
                        '<br>文件路径：' + form.msg[i].url +
                        '<br>MarkDown：![' + form.msg[i].filename + '](' + form.msg[i].url + ')' +
                        '<br><pre>HTML：&lt;img src="' + form.msg[i].url + '"&gt;</pre>' +
                        '</strong>' +
                        '</div>';
                    $('.output').append(text);
                }
            }
        });
        $(document).ready(function () {
            $("#test-upload").fileinput({
                'theme': 'fas',
                'showPreview': false,
                'allowedFileExtensions': ['jpg', 'png', 'gif','mp4', 'gz', 'zip', 'exe', 'xz', 'tar'],
                'elErrorContainer': '#errorBlock'

            });
            $("#kv-explorer").fileinput({
                'theme': 'explorer-fas',
                'uploadUrl': '#',
                overwriteInitial: false,
                initialPreviewAsData: true,
            });
        });
    </script>

{% endblock %}
{% block foot %}
{% endblock %}

templates/nav/videolist.html
{% extends 'template.html' %}
{% block title %}
    <title>教学视频</title>
    {% load static %}
    {% load myfilter %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/video/style.css' %}"/>
{% endblock %}
{% block content %}
    <div class="main" style="padding-top: 80px">
        <form action="" id="desc">
            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="video_type">
                {% for i in desc %}
                    {% if i == selected %}
                        <option selected value="{{ i }}">{{ i }}</option>
                    {% else %}
                        <option value="{{ i }}">{{ i }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <button class="w-100 btn btn-lg btn-primary" type="submit">提交</button>
        </form>
        <script>
            $(function func() {
                    var form = document.getElementById('desc');
                    form.submit();
            })
        </script>
        <div class="dy-content">
                <div class="dy-videos">
                    <ul class="dy-video-list">
                        {% for i in data %}
                            {% if forloop.counter|quyu:5 %}
                                <li data- class="dy-video-item dy-video-meta-left">
                                    {% else %}
                                <li data- class="dy-video-item dy-video-meta-right">
                            {% endif %}
                        <div class="dy-video-meta">
                            <div class="dy-video-meta-bg"></div>
                            <div class="dy-video-meta-dy">
                                <h5 class="dy-video-title" style="font-size: 10px">{{ i.video_title }}</h5>
                                <span style="font-size: 10px">文件大小：{{ i.video_size|filesizeformat }}</span> <br>
                                <span style="font-size: 10px">上传用户：{{ i.username }} </span> <br>
                                <span style="font-size: 10px">上传时间：{{ i.video_time }}</span> <br>
                                <span style="font-size: 10px"><a href="{% url 'App:videoDownload' i.id %}">点击下载</a></span>
                                <p class="dy-video-intro">本视频由千锋云计算持续维护，加速通道正在开发当中。</p>
                            </div>
                            <div class="dy-video-meta-bg"></div>
                        </div>
                        <div class="dy-video-poster"><a
                                href="{% url 'App:videoView' i.id %}"
                                class="dy-video-link"> <img class="dy-video-img" src="{{ i.video_image }}"
                                                            alt="{{ i.video_title }}"> <span
                                class="dy-video-nocomplete"></span> <span
                                class="dy-video-date">{{ i.video_time }} </span> <span
                                class="dy-video-bg"></span> <span class="s-pay"></span> </a></div>
                        <div class="dy-video-primary">
                            <h4 class="dy-video-title">{{ i.video_title }}</h4></div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
        </div>
    </div>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{msg.message}}');
            {% endfor %}
        </script>
    {% endif %}
{% endblock %}

templates/nav/videoview.html
{% extends 'template.html' %}
{% block title %}
    {% load static %}
    <html lang="cn" style="overflow: hidden">
    <head>
        <link href="{% static 'css/video/main-css.css' %}" rel="stylesheet">
    </head>
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>视频播放</title>
    <style>
        html, body {
            width: 100%;
            height: 80%;
            background-color: #292929;
        }

        * {
            padding: 0;
            margin: 0;
        }

        /* 设置视频外部容器样式 */
        #videoContainer {
            width: 1200px;
            height: 650px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 80px;
        }
    </style>
{% endblock %}
{% block content %}
    <!-- 设置视频插件容器 -->
    <div style="background-color: #5c636a">
        <div id="videoContainer"></div>
        <script type="text/javascript" src="{% static 'js/video/superVideo.js' %}"></script>
    </div>
    <script>
        /* 以下将定义视频插件常用的几个控件 */
        // 实例化一个“下一个”按钮控件
        var nextControl = new Super.NextControl()
        // 实例化一个倍速控件
        var Dbspeen = new Super.DbspeenControl()
        // 实例化一个弹幕输入框控件
        var BarrageControl = new Super.BarrageControl()
        // 实例化一个全屏按钮控件
        var fullScreenControl = new Super.FullScreenControl()
        // 实例化视频播放资源
        var source = new Super.VideoSource({
            // type: 视频类型 mp4:可播放浏览器支持的常见格式的视频文件(mp4/ogg/webm) m3u8: 可播放Hls形式推流直播视频(***.m3u8) flv: 可播放flv视频
            // src: 视频路径，可以是本地路径亦可是网络路径
            type: 'mp4',
            src: '{% url "App:stream_video" %}?path={{ path }}'
        })

        /* 插件的常用配置参数 */
        var config = {
            // 是否自动播放（该功能受限于浏览器安全策略，可能会失效，解决思路为初始化时设置为静音，加载完毕后取消静音）
            autoplay: false,
            currentTime: 0, // 设置视频初始播放时间，单位为秒
            loop: false, // 是否循环播放
            muted: false, // 是否默认静音
            playbackRate: 1, // 视频默认播放速度
            poster: '', // 视频首帧图片路径
            volume: 0.5, // 视频默认音量 0-1
            showPictureInPicture: true, // 是否启用画中画模式按钮（>=Chrome10有效）
            source: source, // 为视频插件设置资源
            leftControls: [nextControl], // 在底部控件栏左侧插入 “下一个”按钮控件
            rightControls: [Dbspeen, fullScreenControl], // 在底部控件栏左侧插入 “倍速” 控件和 “全屏” 控件
            {#centerControls: [BarrageControl] // 在底部控件栏中间插入 “弹幕输入控件”#}
        }

        //初始化插件superVideo('videoContainer')请对应好html中的插件容器id.
        var video = new Super.Svideo('videoContainer', config)

        /* 以下是控件类常用的监听事件 */

        // 监听“下一个”按钮控件点击事件
        nextControl.addEventListener('click', function (event) {
            alert('暂不支持')
        })
        // 监听进入全屏模式后触发（点击进入全屏按钮）
        fullScreenControl.addEventListener('fullscreen', function (event) {
            console.log('is fullscreen !!!')
        })
        // 监听退出全屏模式后触发（点击退出全屏按钮）
        fullScreenControl.addEventListener('cancelfullscreen', function (event) {
            console.log('cancel fullscreen !!!')
        })
        // 监听发送弹幕输入框输入并发送弹幕后触发
        BarrageControl.addEventListener('send', function (event) {
            var value = event.target.option.value
            console.log('send ' + value)
        })

        /* 以下是video类常用的监听事件 */
        // 视频准备就绪
        video.addEventListener('ready', function () {
            console.log('is ready!')
        })
        // 开始播放
        video.addEventListener('play', function () {
            console.log('is play!')
        })
        // 暂停播放
        video.addEventListener('pause', function () {
            console.log('is pause!')
        })
        // 监听进入全屏模式后触发
        video.addEventListener('fullscreen', function (event) {
            console.log('is fullscreen !!!')
        })
        // 监听退出全屏模式后触发
        video.addEventListener('cancelfullscreen', function (event) {
            console.log('cancel fullscreen !!!')
        })

        {#/* 下面将演示弹幕类的用法 */#}
        {##}
        {#// 初始化一个弹幕实例#}
        {#var barrage1 = new Super.Barrage('我是一条红色的超大号字体弹幕', {#}
        {#  color: 'red',#}
        {#  fontSize: 30#}
        {# })#}
        {#// 将该弹幕加入播放器插件#}
        {#video.addBarrage(barrage1)#}
        {##}
        {#// 还可以在弹幕中插入一些dom节点#}
        {#var vipDom = document.createElement('span')#}
        {#vipDom.innerHTML = 'V'#}
        {#vipDom.style.color = 'green'#}
        {#vipDom.style.fontSize = '20px'#}
        {#vipDom.style.fontWeight = '600'#}
        {#vipDom.style.marginRight = '4px'#}
        {#var barrage2 = new Super.Barrage('我是超级会员VIP', {#}
        {#  color: 'orange',#}
        {#  fontSize: 15,#}
        {#  leftDom: vipDom // 将DOM插入弹幕左侧#}
        {# })#}
        {#video.addBarrage(barrage2)#}
        {##}
        {#// 当然也可以这样简单的使用#}
        {#video.addBarrage('冲鸭~~~~~~')#}
        {#video.addBarrage('奥里给！！！！！！')#}

        /*
          说在最后：
          superVideo还有许多实用的方法/事件/属性，想深入使用的请参考API文档 —— https://hulalalalala.github.io/superVideo/api/index.html
          开源不易，希望各位爱心人士点个STAR支持以下 —— https://github.com/hulalalalala/superVideo
        */
    </script>
{% endblock %}
{% block foot %}
{% endblock %}